### ISSUE TITLE
edit.gif icon missing in fg_savedata_tabview with Plone 4.3

### ISSUE THREAD

**Issue by acsr** [smcmahon/Products.PloneFormGen#100]
fg_savedata_tabview_p3.pt uses explicit code to get the edit icon as .gif which is deprecated.

see https://github.com/smcmahon/Products.PloneFormGen/blob/master/Products/PloneFormGen/skins/PloneFormGen/fg_savedata_tabview_p3.pt#L56

Solution suggestion: similar to or in conjuction with:
https://github.com/smcmahon/Products.PloneFormGen/commit/f93954a82d3092350afb19f615d9fcff429ceacc

Remark: Not sure how fix this myself and avoid duplicated code or dependency to quickedit.py to render the icon extension in the tabview (because of the p3 suffix).

Is there a more general approach?
Why not use CSS styling for the icons instead of referencing the image?

Since Retina displays it should be obvious to avoid every attempt to use explicitly pixel data in code from my point of view...

**Comment by smcmahon** [comment]
Fixed.
