### ISSUE TITLE
Some field do not have red button box next to them if it is required. 

### ISSUE THREAD

**Issue by domingue** [smcmahon/Products.PloneFormGen#133]
Text, string, line, checkbox, whole number fields are just some that do not have the red box next to the required fields in a form. I noticed that in the HTML, the lines that do not have the box next to it has an added property that says for="name-of-required-field". The fields that do have box next to it do not have the extra expression in the label field.

**Comment by smcmahon** [comment]
The "red box" required indicator is applied by stylesheet on the <span class="required" title="Required">&nbsp;</span> element. The style usually comes from the authoring.css tylesheet.
