### ISSUE TITLE
Mail recipient is not escaped properly

### ISSUE THREAD

**Issue by uschwarz** [smcmahon/Products.PloneFormGen#134]
The `mailerAdapter`'s `recipient_name` and `recipient_email` seem to make up the To header in the form 

    To: recipient_name <recipient_email>

This is insufficient if recipient name contains a comma: 

    To: Smith, John <nowhere@invalid.example>

generated two recipients, one "Smith", one "John <nowhere@invalid.example>", the first of which will usually fail.

To reproduce (at least up to 1.7.16), give a recipient name with a comma and observe the header of the mail you get and the error logs of the mailhost.

**Comment by smcmahon** [comment]
Fixed. Thanks!
