### ISSUE TITLE
FormFolder does not appear in navigation in Plone 5

### ISSUE THREAD

**Issue by pbauer** [smcmahon/Products.PloneFormGen#157]
pfg nees a registry.xml with:

```
  <records interface="Products.CMFPlone.interfaces.INavigationSchema"
           prefix="plone">
    <value key="displayed_types" purge="False">
      <element>FormFolder</element>
    </value>
  </records>
```

**Comment by neilferreira** [comment]
On a similar note to this issue,  are you aware of a way to prevent the thank you page from appearing in the default Plone 5 navigation portlet?    This is when you've successfully submitted the form.

![screenshot from 2015-11-09 17 43 01](https://cloud.githubusercontent.com/assets/1369584/11030486/5fa90cdc-8709-11e5-8e04-66af88a0c3b2.png)

**Comment by richardtc** [comment]
I also cannot see the formfolder in the navigation. I've tried adding to portal_properties/site_properties as default_page_types / FormFolder / Lines, but still unable to see the formfolder in the navigation.

Plone 5.0.5 on Centos6.8

**Comment by richardtc** [comment]
OK, missed it, simply go to /@@navigation-controlpanel in site setup
