### ISSUE TITLE
How to remove the "Creators" tab from PFG Edit Form

### ISSUE THREAD

**Issue by neilferreira** [smcmahon/Products.PloneFormGen#158]
Hello

I'm not very familiar with how Archetype objects work.   How would I go about removing the "Creators" tab from the PFG edit form?  I do not want any users in the CMS to have access to this field.  

Are these setup similar to Dexterity behaviours?

Thankyou.

**Comment by davisagli** [comment]
Easiest workaround: hide it using CSS.

Otherwise you can use archetypes.schemaextender to modify the schema, which is a programming task.

**Comment by neilferreira** [comment]
I've gone for that solution.

ty.
