### ISSUE TITLE
1.7.18 was wrongly released as 1.7.19

### ISSUE THREAD

**Issue by hvelarde** [smcmahon/Products.PloneFormGen#163]
See:

- https://pypi.python.org/pypi/Products.PloneFormGen/1.7.18
- https://pypi.python.org/pypi/Products.PloneFormGen/1.7.19

The changelog is wrong now.

**Comment by mauritsvanrees** [comment]
Ah, good point. I have updated the history in a90c55c2caa922ef3d3fc441c1d4bf06ddaad080.
Quoting the commit message:

> Both versions are valid and contain the fix. We recommend using 1.7.19.
> I have uploaded the missing 1.7.18 to PyPI and have edited the PyPI page of 1.7.19, without changing its download.
