### ISSUE TITLE
Plone 5: CaptchaField is available but not appear on "add menu"

### ISSUE THREAD

**Issue by keul** [smcmahon/Products.PloneFormGen#168]
Installing PloneFormGen on Plone 5 will not show some valid subitems in the add menu:

* I can't see the the Label item
* I can't see the Recaptcha field (recaptcha in installed)
* ... other

Strange thing: you *can* manually add those items by typing and URL like:

    http://localhost:8080/Plone/my-form/portal_factory/FormCaptchaField/....

So it only seem an issue of the add menu... maybe is a Plone bug when you have too many items?

**Comment by keul** [comment]
Found that is a Plone issue.

**Comment by gwarah** [comment]
I have plone 4.3 and got same problem. Solve it issue creating this workflow settings

![image](https://user-images.githubusercontent.com/5703210/84934725-1e74f180-b0ae-11ea-9997-b69ef858a6a5.png)
