### ISSUE TITLE
Unauthorized: Cannot create FormStringField

### ISSUE THREAD

**Issue by zopyx** [smcmahon/Products.PloneFormGen#171]
Plone 5.0.5, logged in as admin, trying to create a FormFolder (PFG 1.8.1):

2016-07-08 11:47:33 ERROR Zope.SiteErrorLog 1467971253.620.400135526887 http://omicron.fhlb.ch:5080/omicron/de/portal_factory/FormFolder/formfolder.2016-07-08.2521974078
Traceback (innermost last):
  Module ZPublisher.Publish, line 127, in publish
  Module ZPublisher.BaseRequest, line 508, in traverse
  Module ZPublisher.BaseRequest, line 352, in traverseName
  Module ZPublisher.BaseRequest, line 135, in publishTraverse
  Module Products.ATContentTypes.tool.factory, line 222, in __getitem__
  Module Products.ATContentTypes.tool.factory, line 77, in _createObjectByType
  Module Products.CMFCore.TypesTool, line 552, in _constructInstance
  Module Products.PloneFormGen.content.form, line 7, in addFormFolder
  Module Products.PloneFormGen.content.form, line 866, in initializeArchetype
  Module Products.ATContentTypes.lib.constraintypes, line 290, in invokeFactory
  Module Products.CMFCore.PortalFolder, line 292, in invokeFactory
  Module Products.CMFCore.TypesTool, line 833, in constructContent
  Module Products.CMFCore.TypesTool, line 309, in constructInstance
Unauthorized: Cannot create FormStringField

**Comment by keul** [comment]
@zopyx while I'm reporting other issues I tried to reproduce this without luck (same Plone and PFG versions)

**Comment by zopyx** [comment]
Also can't reproduce it again since we kicked PFG from this particular project...closing :-)
