### ISSUE TITLE
Enabled Plone Theme Classic for loadtest profile

### ISSUE THREAD

**Issue by macagua** [smcmahon/Products.PloneFormGen#177]
Hi @smcmahon 

When run the buildout create a plone site using **"loadtest"** profile, don't it's enabled the _"Plone Theme Classic"_, and the demo site don't look nice!

Look the following image: 

![2016-11-17 19 02 17](https://cloud.githubusercontent.com/assets/185395/20411617/95ebae24-acf8-11e6-8398-4cf457995eeb.png)

**Comment by mauritsvanrees** [comment]
This is fixed with the merge of your pull request #179.
