### ISSUE TITLE
UnicodeDecodeError with umlauts or euro sign in 1.7.20: 'ascii' codec can't decode...

### ISSUE THREAD

**Issue by jnachtigall** [smcmahon/Products.PloneFormGen#182]
Follow-Up of http://stackoverflow.com/questions/40948196/unicodedecodeerror-in-ploneformgen-after-plone-security-patch-20161129

After upgrading to 1.7.20 I got `UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 20: ordinal not in range(128)`. Details and somewhat of a patch (in the answer) are in the above link.

**Comment by mauritsvanrees** [comment]
Fixed in 1.7.21 and 1.8.3.
