### ISSUE TITLE
verification failed message is incorrect

### ISSUE THREAD

**Issue by tkimnguyen** [smcmahon/Products.PloneFormGen#186]
With collective.recaptcha 2.0.0 the captcha no longer requires you to type in text, but to click a checkbox labeled "I'm not a robot" (and perhaps other things). The verification failed message is currently: "Verification failed: Please type the characters you see below." but should be changed to something like "Verification failed: Please respond to the captcha below"

![untitled](https://cloud.githubusercontent.com/assets/815418/21196418/2a4b4c14-c1fd-11e6-9da5-b47aaa3edcdb.jpg)

**Comment by mauritsvanrees** [comment]
That makes sense. I have merged your pull request #187. Thanks!

**Comment by mauritsvanrees** [comment]
This fix is in release 1.8.4 (today).
