### ISSUE TITLE
Why do I need to reinstall Products.PloneFormGen if I add a captcha later on?

### ISSUE THREAD

**Issue by idgserpro** [smcmahon/Products.PloneFormGen#205]
> [If you add a captcha facility *after* installing PFG, you will need to reinstall PFG (via add/remove products) to enable captcha support.](https://github.com/smcmahon/Products.PloneFormGen/blob/14ac4c4750538b78be63167212b977f12a456b4f/docs/README_CAPTCHA.txt#L14)

Checking the source code, it seems *overkill* to reinstall the package only to add captcha support, since what reinstall does is [re-add `FormCaptchaField` as an allowed content type to `FormFolder` if there's a multi adapter named `captcha`](https://github.com/smcmahon/Products.PloneFormGen/blob/f8aa1d7f9ec311bc44283cb81fb2a9861bdbc087/Products/PloneFormGen/setuphandlers.py#L108...L120): this can be acomplished either by reinstalling the component or editing it in the ZMI at http://localhost:8080/Plone/portal_types/FormFolder.

Wouldn't it be the case to update the docs stating that (don't forget https://docs.plone.org/working-with-content/managing-content/ploneformgen/captcha.html as well)? Or am I missing something that more people familiar with this package know more than me?

**Comment by mauritsvanrees** [comment]
In the current Plone UI, reinstall is the only way to do this. That is why we have this text.
Alternatively, the PloneFormGen control panel could link to a small form that adds `FormCaptchaField` to the list.
Or we can always allow to add the `FormCaptchaField`, and make it smarter: display an informative message for the editor when no captcha facility is installed, and do not display anything for the user.

**Comment by idgserpro** [comment]
> In the current Plone UI, reinstall is the only way to do this. 

What do you think of adding a second option to docs, to use http://localhost:8080/Plone/portal_types/FormFolder? Does it really solve the problem or running reinstall is a must? Then we can have two options.

> Alternatively, the PloneFormGen control panel could link to a small form that adds FormCaptchaField to the list. Or we can always allow to add the FormCaptchaField, and make it smarter: display an informative message for the editor when no captcha facility is installed, and do not display anything for the user.

These ideas look nice but I don't think it's worth to spend time in these implementations... Usually, people will search for "captcha Products.PloneFormGen" and look for the docs, having two options: reinstall or going directly to portal_types.

**Comment by mauritsvanrees** [comment]
As far as I know, editing the `portal_types/FormFolder` in the ZMI is enough. So adding that to the docs seems good. I dislike having to reinstall PloneFormGen (or any product).

**Comment by idgserpro** [comment]
@mauritsvanrees PR added.
