### ISSUE TITLE
Travis doesn't check PRs?

### ISSUE THREAD

**Issue by sneridagh** [smcmahon/Products.PloneFormGen#211]
I just realised that Travis isn't checking my (external) PR...

**Comment by mauritsvanrees** [comment]
Is this still true? You did get a Travis build on https://travis-ci.org/smcmahon/Products.PloneFormGen/builds/348254761. Or did you start that manually maybe?

**Comment by sneridagh** [comment]
It should have been a Github glitch, it didn't show me any jobs at the bottom of the PR. Sorry!

**Comment by mauritsvanrees** [comment]
No problem! 👍
