### ISSUE TITLE
Forms and Site Setup Configuration broken under Plone 5.2.0

### ISSUE THREAD

**Issue by alexsielicki** [smcmahon/Products.PloneFormGen#220]
When visiting a form or Site Setup > PloneFormGen, I get an error page. This started happening after upgrading to Plone 5.2.0, but also happens in a fresh 5.2.0 instance. For buildout's eggs, I have the following:

> eggs =
>     Plone[archetypes]
>     Pillow
>     Products.PloneFormGen

When visiting a form, I get this message:

> This page does not seem to exist…
> 
> We apologize for the inconvenience, but the page you were trying to access is not at this address. You can use the links below to help you find what you are looking for.
> 
> If you are certain you have the correct web address but are encountering an error, please contact the site administration.
> 
> Thank you.

When visiting Site Setup > PloneFormGen, I get this message:

> We’re sorry, but there seems to be an error…
> 
> If you are certain you have the correct web address but are encountering an error, please contact the site administration.

Nothing appears in the console when I visit a form or the site setup config.

**Comment by mauritsvanrees** [comment]
I have released 1.8.8, which fixes viewing forms and the control panel in Plone 5.2.
