### ISSUE TITLE
AttributeError: Macro captchaField_widget does not exist for <FormFolder at online-event-registration>

### ISSUE THREAD

**Issue by richardtc** [smcmahon/Products.PloneFormGen#23]
Unable to view previously created form content on importing zexp into fresh zope instance.

Plone 413 /Products.PloneFormGen = 1.7rc1

Error
  Module zope.tales.tales, line 696, in evaluate
- URL: file:/home/user/plone413/buildout-cache/eggs/Products.PloneFormGen-1.7rc1-py2.6.egg/Products/PloneFormGen/skins/PloneFormGen/fg_edit_macros_p3.pt
- Line 97, Column 20
- Expression: <PythonExpr here.widget(field.getName(), mode='edit', field=field)>
- Names:
    {'container': <FormFolder at /epditemplate/demo-core-products/forms-surveys/online-event-registration>,
     'context': <FormFolder at /epditemplate/demo-core-products/forms-surveys/online-event-registration>,
     'default': <object object at 0xb77977d0>,
     'here': <FormFolder at /epditemplate/demo-core-products/forms-surveys/online-event-registration>,
     'loop': {u'field': <Products.PageTemplates.Expressions.PathIterator object at 0xb40be6ac>},
     'nothing': None,
     'options': {'args': (),
                 'state': <Products.CMFFormController.ControllerState.ControllerState object at 0xb40c246c>},
     'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0xb447e93c>,
     'request': <HTTPRequest, URL=http://localhost:8080/epditemplate/demo-core-products/forms-surveys/online-event-registration/fg_base_view_p3>,
     'root': <Application at >,
     'template': <FSControllerPageTemplate at /epditemplate/demo-core-products/forms-surveys/online-event-registration/fg_base_view_p3>,
     'traverse_subpath': [],
     'user': <User 'admin'>}
  Module Products.PageTemplates.ZRPythonExpr, line 48, in **call**
- **traceback_info**: here.widget(field.getName(), mode='edit', field=field)
  Module PythonExpr, line 1, in <expression>
  Module Products.Archetypes.BaseObject, line 284, in widget
  Module Products.Archetypes.Renderer, line 24, in render
  Module Products.Archetypes.generator.widget, line 145, in **call**
  AttributeError: Macro captchaField_widget does not exist for <FormFolder at online-event-registration>

**Comment by tkimnguyen** [comment]
I think this was fixed in https://github.com/smcmahon/Products.PloneFormGen/pull/83
