### ISSUE TITLE
PicklistWidget error in modal popin (in quickedit when you click on edit adapter, loaded with prepOverlay)

### ISSUE THREAD

**Issue by fbrun** [smcmahon/Products.PloneFormGen#95]
Hi,
on v1.7.12, when i click on the edit button in quickedit, on form save adapter for exemple, then a modal popin is opened thanks to prepOverlay function.

But the problem is no javascript is loaded on this popin, so i have an error like "ReferenceError: pick_moveKeywords is not defined" on field type PicklistWidget.

I find a potential solution by forcing, in quickedit.js file, in $('.editHook a[href$=edit]').prepOverlay function, the load of the needed javascript:

config: {
            onBeforeLoad : function (e) {
                this.getOverlay().prepend("&lt;script src='widgets/js/picklist.js' charset='iso-8859-1' type='text/javascript' /&gt;");
                return true;
            }
        }

Sorry for my bad english
Thanks

**Comment by reinhardt** [comment]
Thanks!
